### ISSUE TITLE
About the  test metric

### ISSUE THREAD

**Issue by ThyrixYang** [martius-lab/blackbox-backprop#1]
Hi,

I've seen your poster at NeurIPS 2019 workshop and have a deep impression.

I'm confused about the test metric. Typically in tasks like shortest path or TSP, the solutions are compared by their value, not the accuracy of optimal. I wonder how the approximation ratio looks like since neither proposed method nor resnet can give a perfect solution, do they look similar?

**Comment by martius-lab** [comment]
Yes, we were internally measuring also approximation ratio (or actually the percentage of prediction within a certain error range, such as 1%, 0.1% etc). The results looked very similar to those reported in the paper and we didn't see much value in adding them. So the ResNet baseline is still bad and the hybrid architectures work fine (but keep in mind that these were synthetic tasks built to have high combinatorial complexity so we are not making a general claim there)

We should be able to dig them up if you are interested.

**Comment by ThyrixYang** [comment]
Thanks for your reply. I think it's necessary to know how bad the baseline is, a histogram may be the best choice so that we can know how many results are in e.g. 1% or 5% error range. And for some practical usage, it's also necessary to know how far the proposed method deviates from optimal if it's not optimal.

**Comment by mrolinek** [comment]
I am afraid, we won't find the energy to add additional results to our paper :/.

However, we did keep track of these metrics during development. In fact, if you can run the code from the [wider codebase](https://sites.google.com/view/combinatorialgradients/home), you will see the numbers for the shortest path problems. 

The baseline was terrible; it in fact almost never returned a valid path (matching, tsp tour) so this metric was even hard to measure.

Please, don't take this as an effort to hide anything, we simply did not report the numbers as they communicated the exact same message as the main numbers (hybrid architectures are really good, the baseline is really bad). Also, this statement should be viewed in the context of our **synthetic datasets**. On real datasets, the situation may be more complicated, please take a look at our recent work (linked from this repo -- about to be populated)
