### ISSUE TITLE
Datasets and experiments?

### ISSUE THREAD

**Issue by bkj** [martius-lab/blackbox-backprop#2]
Hi --

Are there any pointers to datasets and experiments that I could run w/ this code?  I'm very interested in trying to apply these methods to one of my research projects, so any more information you can give would be very helpful.

Thanks!

**Comment by mrolinek** [comment]
Hi! Sorry for the late reply and thank you for the interest in our work.

For one, the torch modules should be reasonably well documented.

Also, there is a [wider codebase](https://sites.google.com/view/combinatorialgradients/home) for the shortest path solver (including a dataset).

Additionally, we will populate a [new repository](https://github.com/martius-lab/blackbox-deep-graph-matching) for our new paper within hours. This will include more usage examples.
