### ISSUE TITLE
Can you provide the whole code of this paper?

### ISSUE THREAD

**Issue by machanic** [martius-lab/blackbox-backprop#5]
I found  that the code in this repo is only a part of your paper, which is the back propagation function. Can you provide the whole code so that I can reimplement the experiments.

**Comment by mrolinek** [comment]
Thank you for interest in our work.

We regarded the construction of the "differentiable solvers" as the key contribution and primarily released these torch modules as we found them to be most valuable for the community.

The tasks we constructed and solved are not recognized benchmarks and were not intended to become ones.

For these reasons, we will probably not maintain a repository supporting all of our experiments. Unless there is significant interest.

Having said that, the code for reproducing the shortest path experiment can be downloaded [here](https://sites.google.com/view/combinatorialgradients/home) (this link is also in the readme). We will shortly extend this code to cover more of our experiments but as I said, we probably will not invest time and energy into polishing the code and maintaining a large separate repository.

**Comment by ereday** [comment]
Dear @mrolinek , 

Thanks for such a nice repository and sharing additional resources for Shortest path experiment. 

I was wondering whether the same thing could also be possible for traveling sales man problem? It would be great to have an example code showing how Gurobi optimizer can be used together with the NN model.
