### ISSUE TITLE
How to deal the case that the solver inputs and outputs tensors with different shapes?

### ISSUE THREAD

**Issue by machanic** [martius-lab/blackbox-backprop#6]
How to deal the case that the solver inputs and outputs tensors with different shapes?

Suppose the solver's output shape is different from the shape of its input, which leads to `grad_output_numpy`'s shape is different from `ctx.weights`, and then the following code will report error due to shape conflict in the addtion operator.

`weights_prime = np.maximum(ctx.weights + ctx.lambda_val * grad_output_numpy, 0.0)`
In https://github.com/martius-lab/blackbox-backprop/blob/master/blackbox_backprop/shortest_path.py#L93

This case may happen frequently, for example, the solver is a image classifier, input is `224x224x3` image and output is a classification probability vector.

**Comment by georgmartius** [comment]
The blackbox solver that we deal with here is defined as: y*=argmin y^T w (subject to constraints). So the cost function is an inner product where input (w) and output (y) have the same shape.

In your case the input image needs to be processed by a network to produce the input that the solver can work with. E.g. edge weights of a grid-like graph.

**Comment by mrolinek** [comment]
Indeed, an image classifier is not an example of a combinatorial solver.

The solver really needs to be a minimizer of an inner-product objective, as it is common in combinatorics.

Closing this.
