### ISSUE TITLE
Multiply combinatorial gradient by grad_output

### ISSUE THREAD

**Issue by amoskalev** [martius-lab/blackbox-backprop#7]
Hello, amazing work!

Shouldn't you multiply the gradient of combinatorial layer by grad_output when you implement backward?

Take for example `TspSolver `function from `blackbox-backprop/blackbox_backprop/travelling_salesman.py `. 
Shouldn't the resulting gradient in backward be `gradient = grad_output*(-(ctx.suggested_tours - better_tours) / ctx.lambda_val)`?

Thanks!

**Comment by mrolinek** [comment]
Hi!

Thanks for your interest!

This is, in fact, on purpose. Blackbox differentiation does not output the Jacobian of the transformation but *directly* the "output" gradient.

It is further explained on page 4 [in the paper](https://openreview.net/pdf?id=BkevoJSYPB)

cheers,

Michal
